### ISSUE TITLE
Can not make array that have `Array.maxLen` size.

### ISSUE THREAD

**Issue by yonta** [smlsharp/smlsharp#58]
OS: Ubuntu 18.04 in WSL2
Compiler: SML# v3.5.0 installed by Tohoku Univ apt repository.

SML# compiler does not allow to make a array that size is less than `Array.maxLen`.
Example code is below.

```sml
(* bug.sml *)
val arrayLen = Array.maxLen div 4    (* OK size, equals 0x3ffffff *)
val bigArray = Array.array (arrayLen, 0)
val n = Array.sub (bigArray, arrayLen - 1)
val () = print (Int.toString n)
val () = print "\n"

val arrayLen = Array.maxLen div 4 + 1    (* NG size *)
val bigArray = Array.array (arrayLen, 0)
val n = Array.sub (bigArray, arrayLen - 1)
val () = print (Int.toString n)
val () = print "\n"
```
```
$ smlsharp bug.sml && ./a.out
0
uncaught exception: Size at src/basis/main/Array_common.sml:53.18
中止
```

In REPL, threshold of error is difference.

```sml
SML# 3.5.0 (2019-12-24 17:29:31 JST) for x86_64-pc-linux-gnu with LLVM 7.0.0
# val arrayLen = Array.maxLen div 8 + 1;
val arrayLen = 33554432 : int
# val bigArray = Array.array (arrayLen, 0);
uncaught exception Size at src/basis/main/Array_common.sml:319.18
# val arrayLen = Array.maxLen div 8;
val arrayLen = 33554431 : int
# val bigArray = Array.array (arrayLen, 0);
(* too slow in `SMLSHARP_HEAPSIZE=2G smlsharp` *)
```

**Comment by yonta** [comment]
Other data type cause other error threshold.
A threshold of type `int` is `0x3ffffff`.
Another case, a threshold of type 'int option` is `0x1ffffff`.

```sml
val arrayLen = Array.maxLen div 8    (* OK size, equals 0x1ffffff *)
val bigArray = Array.array (arrayLen, SOME 0)
val n = Array.sub (bigArray, arrayLen - 1)
val () = print (Int.toString (valOf n))
val () = print "\n"

val arrayLen = Array.maxLen div 8 + 1    (* NG size *)
val bigArray = Array.array (arrayLen, SOME 0)
val n = Array.sub (bigArray, arrayLen - 1)
val () = print (Int.toString (valOf n))
val () = print "\n"
```

**Comment by yonta** [comment]
In v3.6.0, there is same  issue.

**Comment by uenoB** [comment]
This is an expected behavior, not a bug.

In SML#, the maximum length of arrays may vary depending on the type of elements because of natural data representation. Hence, there is no single integer representing the limit of the number of array elements. Array allocation functions such as `Array.array` computes the size limit from the size of the element type. This behavior cannot be covered by the Basis Library Manual.

As such, in SML#, the value of `Array.maxLen` is just a placeholder; we choose it the maximum length of `char array`s, which is really the maximum length of arrays supported by this implementation.

**Comment by yonta** [comment]
OK, I got it. Thx!
