### ISSUE TITLE
Build failure on macOS 10.14.6 Mojave with homebrew llvm 12.0.1

### ISSUE THREAD

**Issue by andreasabel** [smlsharp/smlsharp#68]
From current master (471c96c37ab117c422038bf0b2a492d67ffab922) I ran, after `brew install llvm` and successfully installing `massivethreads`:
```
$ ./configure --with-llvm=/usr/local/opt/llvm
...
$ make
```
This ends with an error when trying to run the built executable `minismlsharp`:
```
$ ./minismlsharp 
command failed at status 1: getVersion /usr/local/Cellar/llvm/12.0.1/bin/llc -version
```
Manually running `llc` gives:
```
$ /usr/local/Cellar/llvm/12.0.1/bin/llc -version
Homebrew LLVM version 12.0.1
  Optimized build.
  Default target: x86_64-apple-darwin18.7.0
  Host CPU: broadwell

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    ...
```

**Comment by minoki** [comment]
The problem is, [LLVMUtils.sml](https://github.com/smlsharp/smlsharp/blob/471c96c37ab117c422038bf0b2a492d67ffab922/src/compiler/libs/toolchain/main/LLVMUtils.sml#L42-L46) doesn't recognize the line `Homebrew LLVM version 12.0.1` in the output of `llc`.
(The `Homebrew` part comes from LLVM's `PACKAGE_VENDOR` configuration macro and the code printing it is [here](https://github.com/llvm/llvm-project/blob/09507b53250dc266632c204558cb1c2b56e8ddea/llvm/lib/Support/CommandLine.cpp#L2416-L2421).)

The version detection logic in LLVMUtils.sml should be more robust.
